### ISSUE TITLE
Android M (Preview 3) - "Underflow in restore"

### ISSUE THREAD

**Issue by emhagman** [edmodo/cropper#105]
There is a `.restore()` being called without a matching `.save()` if you using the "circle crop". For now, I will just have Android M use the square crop but it would be nice to have this fixed.

```
09-02 14:57:06.485  30911-30911/us.drafted.drafted.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: us.drafted.drafted.debug, PID: 30911
    java.lang.IllegalStateException: Underflow in restore - more restores than saves
            at android.graphics.Canvas.native_restore(Native Method)
            at android.graphics.Canvas.restore(Canvas.java:540)
            at com.theartofdev.edmodo.cropper.cropwindow.CropOverlayView.drawBackground(CropOverlayView.java:555)
            at com.theartofdev.edmodo.cropper.cropwindow.CropOverlayView.onDraw(CropOverlayView.java:312)
```

**Comment by nickaein-a** [comment]
+1

**Comment by iamMehedi** [comment]
Facing the same issue in Android 6.0

**Comment by GirishBhalerao** [comment]
This has very simple solution. Just downgrade your - targetSdkVersion to 22
It works for all versions.
