### ISSUE TITLE
java.lang.IllegalArgumentException: y must be >= 0

### ISSUE THREAD

**Issue by codeskraps** [edmodo/cropper#119]
Version 1.0.1

Fatal Exception: java.lang.IllegalArgumentException: y must be >= 0
       at android.graphics.Bitmap.checkXYSign(Bitmap.java:366)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:683)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:653)
       at com.edmodo.cropper.CropImageView.getCroppedImage(SourceFile:357)

**Comment by codeskraps** [comment]
May be a duplicate --> https://github.com/edmodo/cropper/issues/71
