### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError on 300+M free device

### ISSUE THREAD

**Issue by arhi** [edmodo/cropper#123]
`Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
       at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmap(BitmapUtils.java:313)
       at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:213)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:467)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:451)
       at com.piip.piiplibrary.fragments.AvatarCropActivityFragment$1.onClick(AvatarCropActivityFragment.java:98)
       at android.view.View.performClick(View.java:4439)
       at android.widget.Button.performClick(Button.java:139)
       at android.view.View$PerformClick.run(View.java:18395)`

or

`Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
       at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmap(BitmapUtils.java:313)
       at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:213)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:467)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:451)
       at com.piip.piiplibrary.fragments.AvatarCropActivityFragment$1.onClick(AvatarCropActivityFragment.java:98)
       at android.view.View.performClick(View.java:4439)
       at android.widget.Button.performClick(Button.java:139)
       at android.view.View$PerformClick.run(View.java:18395)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)`

mostly on samsungs
sm_g900f 43%
gt_i9300 12%
gt_i9505 12%

on android 5.0, 5.0.1, 5.0.2, 4.2.2, 4.3, 4.1.2...

**Comment by arhi** [comment]
this looks similar/same as #46 at least the first type of crash ?!
