### ISSUE TITLE
Bitmap.getWidth() on a null object

### ISSUE THREAD

**Issue by softsnow** [edmodo/cropper#137]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.edmodo.cropper.util.ImageViewUtil.getBitmapRectCenterInside(ImageViewUtil.java:36)
	at com.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:330)

**Comment by realxz** [comment]
I'm having the very same issue, I'd love to hear if someone resolved this!
