### ISSUE TITLE
Crash on android gradle plugin 3.0.1 version

### ISSUE THREAD

**Issue by nlasagni** [edmodo/cropper#145]
Hi,
first of all thank you for sharing your library, it has saved me a lot of implementation time.
I'm using the CropImageView like this:
```
 <com.edmodo.cropper.CropImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:layout_below="@id/toolbar_layout"
        android:layout_marginTop="20dp"
        android:layout_marginBottom="20dp"
        cropper:fixAspectRatio="true"
        cropper:scaleType="fitCenter" />
```

and with android gradle plugin version 2.3.3 i've never had problems, but since i want to update it, now when i try to show that view the app crash with this message:

```
03-15 11:19:46.057 5476-5476/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.mangomobi.tuttodanza, PID: 5476
                                                 java.lang.RuntimeException: Unable to resume activity {com.mangomobi.tuttodanza/com.mangomobi.showtime.app.MainActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class com.edmodo.cropper.CropImageView
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                  Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class com.edmodo.cropper.CropImageView
                                                  Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class com.edmodo.cropper.CropImageView
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                     at com.mangomobi.showtime.module.user.view.CropPictureView.onCreateView(CropPictureView.java:74)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
                                                     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:382)
                                                     at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:488)
                                                     at com.mangomobi.showtime.app.MainActivity.onResume(MainActivity.java:309)
                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                                                     at android.app.Activity.performResume(Activity.java:7101)
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                  Caused by: java.lang.IllegalArgumentException: Cannot set aspect ratio value to a number less than or equal to 0.
                                                     at com.edmodo.cropper.cropwindow.CropOverlayView.setInitialAttributeValues(CropOverlayView.java:331)
03-15 11:19:46.057 5476-5476/? E/AndroidRuntime:     at com.edmodo.cropper.CropImageView.init(CropImageView.java:490)
                                                     at com.edmodo.cropper.CropImageView.<init>(CropImageView.java:101)
```

Any suggestion/fix/workaround? 

Thanks

**Comment by maugagneur** [comment]
I had the same issue.
I solved it using `implementation 'com.edmodo:cropper:2.0.0'` but you will have to deal with https://github.com/edmodo/cropper/issues/125 :-/
